spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/review?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: review
    password: 1234
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mustache:
    servlet:
      expose-request-attributes: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
    org.springframework:
      security: DEBUG

server:
  servlet:
    session:
      timeout: 30m

